@extends('layouts.app')

@section('content')
<div class="container px-5 py-5 my-5" style="margin-top: @if(Auth::user()){{'96px!important'}}@else{{'56px!important'}}@endif">
    <h1 style="font-size: 1.5rem;">VueMe Privacy Policy</h1>
    <p>Date Updated: </p>
    <p>Welcome to the website http://www.VueMe.com, and any other websites, applications, content or services that link to this Privacy Policy (collectively, the “Services”), which websites, applications or services are operated or produced under VueMe.com LLC (“VueMe”). VueMe values the privacy of the users, members and others who visit and use the VueMe Services and wants you to be familiar with how we collect, use and disclose information from and about you.<p>
    <p>By agreeing to this Privacy Policy in your VueMe™ account setup, or by using the VueMe Services, you expressly consent to the information handling practices described in this notice.</p>
    <p>This Privacy Policy applies to VueMe’s™ collection and use of your personal information (i.e., information that identifies a specific person, such as full name, address, telephone number, or e-mail address). It also describes generally VueMe’s™ practices for handling non-personal information (e.g., interests, demographics, and service usage).</p>
    <p><b>The Information VueMe Collects</b></p>
    <p>User-Provided Information: You may provide VueMe with what is generally called “personal information” in the United States and elsewhere or “personal data” in the European Union (such as your name, e-mail address, mailing address, telephone number, credit card number and billing information) if you register for VueMe Services, or upload, purchase, view or download certain content or products from the VueMe Services, or otherwise use the features and functionality of the VueMe Services.</p>
    <p>Cookies Information: When you access the VueMe Services, we may send one or more cookies – small text files containing a string of alphanumeric characters – to your computer. For information about what cookies are, how they work, how VueMe uses them and how to remove them, please see our Cookie Policy.</p>
    <p>Automatically Collected Information: When you access the VueMe Services or open one of our HTML e-mails, we may automatically record certain information from your system by using cookies and other types of tracking technologies. This “automatically collected information” may include Internet Protocol address (IP address), a unique user ID, device type, device identifiers, browser types and language, referring and exit pages, platform type, version of software installed, system type, the content and pages that you access on the VueMe Services, the number of clicks, the amount of time spent on pages, the dates and times that you visit the VueMe Services, and other similar information. Depending on the law of your country of residence, your IP address may legally be considered personal information.</p>
    <p>Information from Other Sources: We may obtain information, including personal information, from third parties and sources other than the VueMe Services, such as advertisers or social media networks for which you have approved our access to information (e.g., information from your Facebook account provided by the Facebook APIs). When you access the VueMe Services through social media networks or when you connect VueMe Services to social media networks, you are authorizing VueMe to collect, store and use such information and content in accordance with this Privacy Policy. We may also obtain information from third parties such as social entertainment platforms regarding your use of such services, including about your use of the content you choose to broadcast through the VueMe Services. If we combine or associate information from other sources with personal information that we collect through the VueMe Services, we will treat the combined information as personal information in accordance with this Privacy Policy.</p>
    <p><b>The Way VueMe Uses Information</b></p>
    <p>VueMe uses the information that you provide or that we collect from or about you: to operate, maintain, enhance, and provide all of the features and services found on the VueMe Services; to improve your experience with the VueMe Services by delivering content which we hope you will find relevant and interesting, including advertising and marketing messages; to allow you to comment on content, and participate in programs; and as necessary to comply as a service provider with the Digital Millennium Copyright Act or other similar legal obligations around the world.</p>
    <p>We will use your e-mail address for administrative communications such as notifying you of major VueMe Services updates, for customer service and membership purposes, to address copyright infringement or defamation issues, or to contact you regarding any content that you have posted to or downloaded from the VueMe Services.</p>
    <p>VueMe may periodically send promotional materials or notifications to you related to the VueMe Services. If you want to stop receiving promotional materials, you can contact customer service or change the notification settings within your online account.</p>
    <p>VueMe uses the information that we collect to understand the usage trends and preferences of our users and members, to improve the way the VueMe Services work and look, and to create new features and functionality.</p>
    <p>VueMe may use “Automatically Collected Information” and “Cookies Information” to maintain and improve the VueMe Services, including to do the following: (a) automatically update the VueMe application(s) on your system; (b) remember your information so that you will not have to re-enter it during your visit or the next time you access the VueMe Services; (c) provide customized third party advertisements, content and information; (d) monitor the effectiveness of third party marketing campaigns; (e) monitor aggregate website usage metrics such as total number of visitors and pages accessed; and (f) track your entries, submissions, and status in any promotions or other activities.</p>
    <p><b>When VueMe Discloses Information</b></p>
    <p>VueMe does not share your personal information with other organizations for their own marketing or promotional uses without your prior express consent. Please be aware, however, that any personal information that you voluntarily choose to display on any publicly available portion of the VueMe Services – such as when you publish content, comments or profile information – becomes publicly available and may be collected and used by others.</p>
    <p>If you connect to a third party service (such as Facebook or Twitter) through an icon or link on the VueMe Services or otherwise link your VueMe account with a third party service, we may share the contents of your posts and associated information (such as your username, the fact that your connection originated from the VueMe Services, and other relevant usage and diagnostic information) with such third party. With your one time consent, we may also send information about the content you watch and your activities on the VueMe Services to such third parties. Once such information is shared, the use of your information will be subject to that service’s privacy policy.</p>
    <p>VueMe may disclose “Automatically Collected Information” and other aggregate non-personal information with interested third parties to assist such parties in understanding the usage and demographic patterns for certain programs, content, services, advertisements, promotions, or other functionality of VueMe.</p>
    <p>VueMe may make both personal and non-personal information available to affiliates that are under common ownership or control with VueMe.</p>
    <p>We may disclose both personal and non-personal information to service providers working on our behalf to: provide website hosting, maintenance, and security services; fulfill orders; conduct data analysis and create reports; offer certain functionality; and assist VueMe in improving the VueMe Services and creating new services features. We require that these parties process such information in compliance with this Privacy Policy, we authorize them to use the information only for the purposes for which it has been provided to them, and we require these parties to use reasonable confidentiality measures.</p>
    <p>VueMe may disclose user or member information if we believe in good faith that such disclosure is necessary to comply with United States state and federal laws (such as U.S. Copyright law) or other applicable laws around the world (e.g., in the country of your residence); or respond to a court order, judicial or other government subpoena, or warrant in the manner legally required by the requesting entity.</p>
    <p>VueMe also reserves the right to disclose user or member information that we believe, in good faith and after making reasonable inquiries, is appropriate or necessary to take precautions against liability to VueMe; protect VueMe from fraudulent, abusive, or unlawful uses; to investigate and defend ourselves against third party claims or allegations to protect the security or integrity of the VueMe Services; or to protect the rights, property or personal safety of VueMe, our users, members or others. We will notify you of these disclosures if we reasonably think we can do so legally and without harming the purpose of the disclosure.</p>
    <p> <b>Your Choices</b></p>
    <p>You may, of course, decline to share your personal information with VueMe, in which case VueMe will not be able to provide to you some of the features and functionality found on the VueMe Services. If you like to access, review, correct, update, suppress, or otherwise limit our use of your personal information you have previously provided directly to us, you may contact our customer service department; or using the mechanism provided below. In your request, please include your e-mail address, name, address, telephone number and specify clearly what information you would like to access change, update, or suppress. We will try to comply with your request as soon as reasonably practicable and any information you give us will be protected by this Privacy Policy.</p>
    <p>You may update, correct, or delete certain of your user information and preferences by visiting your account page once you have logged in to the VueMe Services. You may also request to update, correct, or delete the personal information you have provided to us by contacting customer service.</p>
    <p>To protect your privacy and security, we take reasonable steps to verify your identity before granting you account access or making corrections to your information. You are responsible for maintaining the secrecy of your unique password and account information at all times.</p>
    <p><b>Advertisers and Analytics Providers</b></p>
    <p>We may use third party web analytics services on our website, such as those of Google Analytics and Mixpanel. These service providers use a variety of tracking technologies such as cookies to analyze how users and members use the VueMe Services. The information collected will be disclosed to or collected directly by these service providers, who use the information to evaluate your use of the VueMe Services.</p>
    <p>VueMe may allow advertisers, third party advertising networks and third party advertising serving companies to serve advertisements directly to you within the VueMe Services. By serving these advertisements directly to you, these companies can set their own cookies on your computer and trigger their own web beacons and other tracking technologies to measure the effectiveness of their advertisements, and to collect and track information such as demographic information, inferred interests, aggregated information, and activity to assist them in personalizing the advertising content delivered to you. VueMe does not provide your personal information to these third party ad servers or ad networks without your consent. However, please note that if an advertiser asks VueMe to show an advertisement to a certain audience (e.g., males age 15-18) or audience segment (e.g., males age 15-18 who have participated in certain promotions or features) and you respond to that advertisement, the advertiser or ad server may conclude that you fit the description of the audience that they are trying to reach.</p>
    <p>This Privacy Policy does not apply to, and we cannot control the tracking technologies and activities of, those other advertisers, third party advertising networks, or third party advertising servers. You should consult the respective privacy policies of these advertisers, third party advertising networks, or third party advertising servers.</p>
    <p><b>Our Commitment to Data Security</b></p>
    <p>VueMe uses commercially reasonable physical, managerial, and technical measures designed to protect the integrity and security of your personal information. However, no security precautions or systems can be completely secure. We cannot therefore ensure or warrant the security of any information you transmit to VueMe, and you do so at your own risk. We cannot guarantee that such information may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, managerial or technical safeguards.</p>
    <p><b>Our Commitment to Children’s Privacy</b></p>
    <p>IF YOU ARE UNDER 13 YEARS OF AGE, THEN PLEASE DO NOT USE OR ACCESS THE VueMe SERVICES AT ANY TIME OR IN ANY MANNER.</p>
    <p>The Services are not available to persons under the age of 13. If you are between the ages of 13 and 18 (or between 13 and the age of legal majority in your jurisdiction of residence), you may only use the Services if done so with the full informed consent of your parent or guardian. If you are between the ages of 13 and 18, we reserve the right, but do not undertake the obligation, to restrict your access to the Service and require you to provide written parental consent. Accordingly, we encourage parents or legal guardians of Users between the ages of 13 and 18 to review the parental consent form and this Privacy Policy and determine if they will provide their consent to their child’s participation in the Site and use of the Service. If you have any questions, you may contact our customer service department. Kindly complete, sign and date the parental consent form at the link provided, and then either mail, e-mail or fax it back to VueMe at the address, e-mail or fax number provided. Please also include a copy of your current valid driver’s license. After VueMe receives your written consent, a VueMe representative may contact you to confirm your identity, status as the parent or legal guardian of the indicated child, and that you signed the consent form.</p>
    <p> <b>International Visitors</b></p>
    <p>For users or members of the VueMe Services from the European Union or other non-U.S. territories, please note that any data you enter into the VueMe Services will be transferred outside the EU or those other non-U.S. territories for use by VueMe and its affiliates for any of the purposes described in this Privacy Policy. In addition, because VueMe operates globally, we may make information we gather available to worldwide business units and affiliates under the terms of this Privacy Policy. By providing any data on the VueMe Services, you hereby expressly consent to such transfers of your data to the United States or other countries. For international users or members, please note that laws in the United States may not provide the same level of protection from information (which users or members provide to VueMe or which VueMe collects from users or members in connection with the VueMe Services) as the laws of the user’s or member’s country of residence.</p>
    <p><b>In the Event of Merger or Sale</b></p>
    <p>In the event that VueMe or some or all of the assets related to the VueMe Services are acquired or merged with a third party, we reserve the right, in any of these circumstances, to transfer or assign the information that we have collected from users or members as part of that merger, acquisition, sale or other change of control.</p>
    <p><b>Changes and Updates to this Privacy Policy</b></p>
    <p>VueMe reserves the right to change, modify, add, or remove portions of this Privacy Policy at any time (for example to reflect updates to the VueMe Services or to reflect changes in the law). If VueMe changes this Privacy Policy, we will provide you notice of these changes, such as by sending you an e-mail, posting a notice on the VueMe Services, or updating the “Last Updated” date above. Please check this Privacy Policy periodically for those changes. Your continued use of the VueMe Service after the posting of changes constitutes your binding acceptance of such changes.</p>
    <p><b>VueMe Contact Information</b></p>
    <p>Please contact VueMe with any questions or comments about this Privacy Policy, your personal information, and our third party disclosure practices or your consent choices at: by e-mail to customer service. We will respond to your inquiry within 30 days of its receipt.</p>

</div>
@endsection