@extends('layouts.app')

@section('content')
<div class="container px-5 py-5 my-5" style="margin-top: @if(Auth::user()){{'96px!important'}}@else{{'56px!important'}}@endif">
    <h1 style="font-size: 1.5rem;">VueMe™ Terms and Conditions</h1>
    <p>Date Updated: </p>
    <p><b>1. Introduction; Acceptance of Terms and Conditions.</b></p>
    <p>
        Welcome to the subscription services platform operated by VueMe.com, LLC, consisting of the website available at  http://www.VueMe.com  (the “Site”), and all related services, software applications and networks that allow for the authorized distribution of pre-recorded content over the internet.
    </p>
    <p>
        These Terms and Conditions (the “Terms”) constitute a binding agreement between an individual subscriber, customer, member, or user (“User(s)” or “you”), and VueMe.com, LLC (“VueMe,” “us” or “we”), and govern the use by Users of the Site and the content, products and services offered through the Site (collectively, the “Services”). IF YOU DO NOT AGREE TO THESE TERMS, YOU SHOULD NOT CHECK OR CLICK ON, OR OTHERWISE AGREE TO, THESE TERMS, AND YOU SHOULD IMMEDIATELY LEAVE THIS PAGE AND NOT ACCESS OR USE THE SITE OR ANY OF THE SERVICES. Upon our request, you agree to sign a non-electronic version of these Terms.
    </p>
    <p><b>2. Changes to Terms of Use and Services.</b></p>
    <p>
        THESE TERMS MAY BE AMENDED OR MODIFIED BY US IN OUR SOLE DISCRETION, WITH OR WITHOUT NOTICE, AT ANY TIME. We indicate on the top of the page when these Terms were last modified. Your continued access or use of the Site or any of the Services following such modifications will be deemed acceptance of such modifications, which will apply on a going-forward basis from such acceptance. In addition, we reserve the right to modify or cease providing all or any portion of the Services at any time, with or without notice. Be sure to return to this page periodically to ensure familiarity with the most recent version of these Terms.
    </p>
    <p><b>3. Privacy Policy.</b></p>
    <p>
        We are committed to protecting the privacy of the personal information you provide to us through the Site. Any personal information submitted through the Site by you is subject to our Privacy Policy, which is incorporated herein by reference. PLEASE REVIEW OUR PRIVACY POLICY TO UNDERSTAND OUR PRACTICES WITH RESPECT TO YOUR PERSONAL INFORMATION. The date of the last modification to our Privacy Policy will be noted at the top of our Privacy Policy.
    </p>
    <p><b>4. Use of Services by Minors and Blocked Persons.

        </b></p>
    <p>
        The Services are not available to persons under the age of 13. If you are between the ages of 13 and 18 (or between 13 and the age of legal majority in your jurisdiction of residence), you may only use the Services if done so with the full informed consent of your parent or guardian. If you are between the ages of 13 and 18, we reserve the right, but do not undertake the obligation, to restrict your access to the Service and may require you to provide written parental consent. Accordingly, we encourage parents or legal guardians of Users between the ages of 13 and 18 to review these Terms and the Privacy Policy for the Site and determine if they will provide their consent to their child’s participation in the Site and use of the Service. Users between the ages of 13 and 18 whose parents or legal guardians do not consent are prohibited from using the Services. If you have any questions, you may contact our customer service department.
        In addition to persons under the age of 13 and those under 18 without parental consent as provided above, the Site and Services are also not available to any Users previously suspended or removed by VueMe (see Section 15 below for more about suspension and removal).

    </p>
    <p><b>5. Account.</b></p>
    <p>
        In order to participate in or receive the Services, you will be required to create an account with us (“Account”), and you may be subject to additional contractual terms and conditions applicable to such Services (“Additional Terms”), which Additional Terms will be accessible to you on the Site or presented to you as Additional Terms when you register for or access such. Any Additional Terms shall be incorporated into and form a part of these Terms. Your Account is for your individual, personal use only, and you may not authorize others to use your Account for any purpose. You will not create more than one account for yourself. In creating your Account, you certify that all information you provide is complete and accurate. You agree to update your information when required or requested, and you further agree not to use another person’s account for any reason. You are responsible for maintaining the confidentiality of, and restricting access to, your Account and password, and you agree to accept sole responsibility for all activities that occur under your Account. You will not buy, sell, rent, or lease access to your VueMe account without our written permission. You agree to contact our customer service department immediately in the event of any breach of security, unauthorized use of your Account, or any violation of these Terms by others of which you are aware. You agree that we shall have no liability for any losses, damages, liabilities or expenses you may incur due to any unauthorized use of your Account, and you agree to indemnify and hold us harmless for any such unauthorized use. We reserve the right to create accounts for quality control and administrative purposes. Such accounts may be publicly viewable.
    </p>
    <p><b>6. Provider and User Content; Assumption of Risk.</b></p>
    <p>
        The VueMe Services consists of a platform for providers of content (“Models”) to produce, upload and distribute content (“Model Content”). The Services may further provide a platform for Users to create, upload and/or display content of their own creation, including audiovisual content, written works posted on message boards, chat and blogs, and other content, including, without limitation, videos, music, images and text (collectively, “User Content”). You understand that when using or accessing the Site or Services, you will be exposed to Model Content and User Content from various groups and individuals, and that VueMe is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Model Content or User Content. You further understand and acknowledge that you may be exposed to Model Content or User Content that is inaccurate, offensive, indecent and/or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against VueMe with respect thereto. VueMe does not endorse any Model Content or User Content, or any opinion, recommendation, or advice expressed therein, and VueMe expressly disclaims any and all liability in connection with such Model Content or User Content. The views and opinions expressed in the Model Content and User Content are solely those of the account which provided such content and not those of the Site. YOU FULLY ASSUME ALL RISK OF LOSS OR HARM ARISING OUT OF YOUR USE OF THE SITE OR SERVICES.
    </p>
    <p>
        All of the provisions in this Section 6 shall apply with equal force if VueMe Content that includes advertorials, native advertising, or sponsorship (“Sponsored Content”). Without limitation, all of Your representations, warranties, indemnification obligations, and other obligations under the Terms of Use will apply equally to Sponsored Content as they would to any other Content You Submit. You are solely responsible for ensuring that Your Sponsored Content complies with all applicable federal, state, and local laws, rules and regulations, including without limitation the Federal Trade Commission’s Guides Concerning Endorsements and Testimonials (“FTC Guidelines”), including all required disclosures and disclaimers.
    </p>
    <p>
        As with other Content, VueMe assumes no liability for Sponsored Content Submitted by you or any other users of the Service, or for any product or service offered by or through Sponsored Content (“Sponsored Products and Services”). You shall be solely liable for Sponsored Content that You Submit to the Service and all elements of it, including without limitation for Sponsored Products and Services and for any other consequences of transmission of Sponsored Content through the Service.
    </p>
    <p>
        In addition to all other termination provisions set forth in the Terms of Use, VueMe reserves the right, but does not undertake the obligation, to terminate immediately Your access to the Service if You fail to make disclosures in any Sponsored Content You Submit in accordance with the FTC Guidelines or as otherwise required by applicable law. Further, in the event that Sponsored Content Submitted by You includes material or promotes products or services which, in VueMe’s™ sole opinion, conflicts with or does not align with VueMe’s™ business, community, ethical or other goals, then VueMe shall have the right (a) to require that You cease submission of the Sponsored Content and/or (b) immediately terminate Your access to the Service.
    </p>
    <p><b>7. Proprietary Rights; Limited License.</b></p>
    <p>
        The Site and Services are owned and operated by VueMe. With the exception of the User Content and Model Content, the data and materials provided on the Site or through the Services, including without limitation, VueMe’s™ trademarks, service marks, logos, visual interfaces, graphics, design, compilation, information, content, software, computer code (including source code or object code), text, pictures, videos, data, sound files, other files and the selection and arrangement thereof (collectively, the “Materials”) are the intellectual property of VueMe and are protected by United States copyright, trade dress, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws (including in your country of residence). Except as expressly authorized by VueMe, you agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, reverse engineer, or otherwise make use of the Materials. All Materials are provided to you solely for your information and personal, non-commercial use. If, with authorization, you download or print a copy of the Materials for personal use, you must retain all copyright, trademark, or other proprietary notices. VueMe reserves all rights not expressly granted in and to the VueMe Service and Materials. Subject to your compliance with these Terms, VueMe hereby grants you a personal, limited, non-exclusive, non-transferable, freely revocable license to access, view and use the Services for non-commercial purposes. As more fully provided below, with respect to the User Content and Model Content all such content is owned by the person or people who provide such content.
    </p>
    <p><b>8. Third Party Links and Pages; Reliance on Content and Advice.</b></p>
    <p>
        The Site or Services may include hyperlinks or banner ads to third party websites, content and/or resources (collectively, “Third Party Content”). You acknowledge and agree that we have no control over and are not responsible for the availability of any such Third Party Content, and we do not endorse any advertising, products, or other materials on or available from such Third Party Content. Each such third party will be governed by their own terms of use and privacy policy separate from our Terms and Conditions and Privacy Policy. Because we cannot control the activities of such third parties, we cannot accept responsibility for any use of your personal information by such third parties. If you visit or link to Third Party Content, you should consult that third party’s terms of use and privacy policy before providing any personal information. You agree that we shall have no liability for any losses, damages, liabilities, or expenses you may incur due to your use of such Third Party Content, and you agree to indemnify us and hold us harmless for any such use.
    </p>
    <p>
        Opinions, advice, statements, offers or other information or content made available through the Services are those of their respective authors, and should not necessarily be relied upon. Such authors are solely responsible for such content. We do not: (i) guarantee the accuracy, completeness, or usefulness of any information through the Services; or (ii) adopt, endorse or accept responsibility for the accuracy or reliability of any opinion, advice or statement made by any party that appears through the Services. Under no circumstances will we or our affiliates be responsible for any loss or damage resulting from your reliance on information or other content posted through the Services or transmitted to or by any of our Users or Models.
    </p>
    <p><b>9. Content Provided “AS IS”; Access to Content.</b></p>
    <p>
        You understand that Model Content and User Content, whether publicly posted or privately transmitted, are the sole responsibility of the person from whom such content originated. We do not control this content and do not guarantee its accuracy, integrity or quality. All such content is provided “AS IS” without representation or warranty of any kind. You agree that under no circumstances shall we be liable to you in any way in connection with any Model Content or User Content, including but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of any content. We claim immunity from liability to the fullest extent permitted by law, and as further provided under the Communications Decency Act, for any content provided by third parties. Neither our actions nor any provision of these Terms is intended to waive, remove or usurp such immunity.
    </p>
    <p><b>10. Non-Commercial Use.</b></p>
    <p>
        The Services are made available for your personal, non-commercial use. You will not use the Services to advertise or solicit any User to buy or sell any products or services nor make any investment. You may not transmit any chain letters, junk or spam e-mail to other Users. Further, you will not use any information obtained from the Services in order to contact, advertise to, solicit, or sell to any User without the applicable User’s prior express written consent. If you breach the terms of this section and/or send or post unsolicited bulk e-mail, spam or other unsolicited communications of any kind through the Services, we reserve all rights, claims and causes of action we may have, statutory or otherwise, including but not limited to, the right to seek statutory penalties for each such unsolicited communication you send through the Services.
    </p>


    <p><b>11. Personal Communications and License to Your Content; Right to Block or Remove Content.</b></p>
    <p>
        You acknowledge and agree that your communications with Models or other Users via chats, conferences, bulletin boards, blogs, posts and any other avenues of communication through the Services are public and not private communications. Therefore, we strongly encourage you to use caution before disclosing any personal information about yourself in your public communications. We are not responsible for information that you choose to communicate to other Users, or for the action of any Model or any other Users or Models, and you agree to indemnify us and hold us harmless from any losses, liabilities, damages or expenses you may incur due to such communications or actions. Except as provided in our Privacy Policy, once you post, send or otherwise make available any content through the services, you expressly grant us, and hereby represent that you have the right to grant us, a perpetual, irrevocable, worldwide, assignable right and license to quote, re-post, use, copy, reproduce, modify, create derivative works of, incorporate into other works, distribute, transmit, broadcast, communicate, publicly display, publicly perform and otherwise exploit such content in any form or media, anywhere, and without any notice or compensation to you of any kind. You hereby grant us all consents, rights and clearances to enable us to use such content for such purposes. Such content may be searchable by, and you may be able to view and search such content on, different websites (i.e., different URLs in the form of “co-brands” or “private labels”) operated by us or our affiliates. Such content may also be searchable by third party search engines, such as Google, Yahoo and Bing.
    </p>
    <p>
        We reserve the right, but not the obligation, to cease transmission of, block or remove any content, including, but not limited to, User Content or Model Content, in whole or in part, that we, in our sole discretion, deem to be in violation of these Terms or otherwise harmful to persons using the Services, regardless of whether such content or its dissemination is unlawful. We retain the right, but not the obligation, to monitor any and all transmissions and postings of content and other materials from time to time to investigate or prevent violations of these Terms. In addition, we may also limit and/or filter the number of e-mails, chat messages, or posts sent or received by any or all Users and/or Models.
    </p>
    <p>Profile pictures may not contain images of:</p>

    <p>
        • Real nude adults, where nudity is defined as: visible genitalia, visible anus, and/or fully nude close-ups of buttocks, or uncovered female nipples; or
        <br>
        <br>
        • Sexual activity which includes sexual intercourse.
        <br><br>

        We reserve the right, within our sole discretion, to restrict the display of nudity or sexual activity in Models’ profile pictures and remove profile pictures that violate these terms.
    </p>
    <p><b>12. Your Additional Representations and Warranties.</b></p>
    <p>You further represent and warrant to us, under penalty of perjury, and covenant as follows: <br><br>

        a) You will not provide or permit unauthorized access or use of the Services or your Account, and will prevent minors from such access or use as set forth in Section 4;<br><br>
        b) Your Account information is current, complete and accurate and you will promptly update all information to keep your Account and billing information complete and accurate in the event of any change (such as a change of billing address, credit card number or expiration date);<br><br>
        c) You have not and will not access or use the Services from any place or jurisdiction where such use is prohibited or contrary to applicable laws, rules, regulations, ordinances, edicts or customs;<br><br>
        d) Your use of the Services is and will be in compliance with all applicable laws, rules, regulations, ordinances, edicts or customs;<br><br>
        e) You will not use any robot, spider, scraper, or other automated measures to (i) access or use the Services, (ii) circumvent any technical measures we use to provide the Services, or (iii) cause harm to us or our affiliates;<br><br>
        f) You will not forge headers or otherwise manipulate identifiers in order to disguise the origin of any content transmitted through the Services;<br><br>
        g) You will not upload, post, e-mail, transmit or otherwise make available any content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, obscene, libelous, invasive of another’s privacy, hateful, or racially, ethnically or otherwise objectionable;<br><br>
        h) You will not upload, post, e-mail, transmit or otherwise make available any content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under non-disclosure agreements);<br><br>
        i) You will not upload, post, e-mail, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, affiliate marketing codes, link referral code, or any other form of commercial solicitation;<br><br>
        j) You will not upload, post, e-mail, transmit or otherwise make available any content that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any person;<br><br>
        k) You will not upload, post, e-mail, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software, hardware, networks, or telecommunications equipment;<br><br>
        l) You will not interfere with or disrupt the Services, or the servers or networks connected to the Services, or disobey any requirements, procedures, policies, or regulations of networks connected to the Services, including using any device, software, or routine to bypass our robot exclusion headers;<br><br>
        m) You will not collect or store personal data about other Users without their consent (including, but not limited to, manually or through the use of scripts, bots or web crawlers) or upload, post, e-mail, transmit, chat or otherwise disclose one or more other Users’ private information; and<br><br>
        n) You will not disclose any personal information (telephone numbers, addresses, last names, URLs, e-mail addresses or usernames to any money transfer service, etc.”) in any User profile that you create.<br><br>
        o) You will not attempt to circumvent any content-filtering techniques we employ, or attempt to access areas or features of the Services that you are not authorized to access.<br><br>
        p) You will not probe, scan, or test the vulnerability of our Services or any system or network.<br><br>
        q) Profile pictures may not contain images of: real nude adults, where nudity is defined as: visible genitalia, visible anus, and/or fully nude close-ups of buttocks, or uncovered female nipples; or sexual activity which includes sexual intercourse. We reserve the right, within our sole discretion, to restrict the display of nudity or sexual activity in Model’ profile pictures and remove profile pictures that violate these terms.<br><br>

    </p>
    <p>PLEASE REPORT ANY VIOLATIONS OF THIS SECTION OR THESE TERMS TO OUR CUSTOMER SERVICE DEPARTMENT IMMEDIATELY.</p>
    <p><b>13. User/Model Interactions and Disputes.</b></p>
    <p>
        You are solely responsible for your interactions with other Users and Models. You understand and agree that we have no obligation to screen our Users or Models; inquire into the background of Users or Models; or attempt to verify the statements of Users or Models. We make no representations or warranties as to the conduct of Users or Models. If you find other Users’ or Models’ information or content to be offensive, harmful, inaccurate and/or deceptive, you may report abuse by contacting support. We reserve the right, but have no obligation, to monitor disputes between you and other Users or Models and/or to terminate or block you and other Users or Models for violations of these terms. Please also use caution, common sense, and safety when using the Services to interact with other Users or Models. We further reserve the right, but have no obligation, to conduct any credit, criminal, or other background checks using publicly available records, at any time, to confirm your compliance with these Terms.
    </p>
    <p>
        In the event that you have a dispute with one or more other Users and/or Models, you hereby release us and our affiliates, shareholders, directors, officers, employees, agents, successors and assigns from any and all claims, demands, damages (actual and consequential), losses and liabilities of every kind or nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way related to such disputes. If you are a California resident, you waive California Civil Code Section 1542 which says: “A general release does not extend to claims which the creditor does not know or suspect exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.”
    </p>
    <p><b>14. User Fees.</b></p>
    <p>
        <b>Viewing Fees. Certain Services provided to Users are subject to content viewing fees (“Content Viewing Fees”). The Content Viewing Fees (e.g., periodic, pay-per-minute, pay-per-view, etc.) for each item of Content are specified to Users when they select specific Content for viewing and may be different for different Content. Content may recur on a periodic basis or per interaction with Content Models (e.g. per text message, phone call, video chat, etc.) all Content is subject to applicable Content Viewing Fees. By electing to view any Content, the User will be deemed to have agreed to pay the Content Viewing Fees applicable to such Content as posted on the Service at the time the User elects to view each item of Content. Content Viewing Fees shall be paid for using credits that Users will purchase which may be redeemed solely for specified Services (“Credits”). Credits, as well as unused balances, may not be redeemed for cash and may not be returned or forfeited for a cash refund, except as may be required by applicable law. In addition, Credits and unused balances are not transferable. </b>
    </p>
    <p> Subscriptions and Renewals. If Users are afforded the opportunity to subscribe to receive certain Content by payment of a periodic subscription fee (“subscriptions”), rather than paying separately for each individual item of Content, then in order to provide continuous service, we may automatically renew all subscriptions for the Services on the day such subscriptions expire. Such renewals shall be (i) for a period equivalent to the period of your initial subscription to the Services or a shorter period of time if specified, and (ii) in our discretion, at the then current price of the same or comparable Services then in effect. In addition, we sometimes offer special promotions that have renewal periods of different duration than the initial subscription term. In all cases, if you do not wish for your subscription to renew automatically, please deactivate auto-renew under your profile settings. </p>
    <p>VueMe reserves the right to suspend or terminate Your access to any Subscription-based part of the Service without notice upon rejection of any charges or if the bank of other entity that makes payment on your behalf (or its agent or affiliate) seeks return of payments previously made when VueMe believes You are liable for the charges. VueMe also reserves the right in its sole discretion to suspend or terminate Your access to any Subscription-based service if You are found, at the sole discretion of VueMe, to be in breach of these Terms, or if You are suspended or banned, for any reason. </p>
    <p> Authorization to Charge. Your non-termination or continued use of the Services reaffirms that we are authorized to charge your chosen payment provider. We may submit those charges for payment and you will be responsible for such charges. This does not waive our right to seek payment directly from you. Your charges may be payable in advance, in arrears, per usage, or as otherwise described when you initially subscribed to, or otherwise joined, the Services. Any change to such billing practice will be posted here and in the Billing Page in your account. </p>
    <p> Account Maintenance Fee. If you have not logged into your Account in the previous 180 days, we reserve the right, in our sole discretion, and without notice or liability to you, to charge you an Account maintenance fee equal to $3.00 per month or, if less than $3.00 remains in your Account, the remaining funds. Your credit card(s) on file with us will not be charged, and you will not incur a negative balance, due to any such Account maintenance fee. </p>
    <p> Transaction Fees. We may use credit card processors or banks (domestic or internationally) to process your transactions. In some instances, banks or credit card processors may charge transaction or similar fees. Such fees are your responsibility. Before purchasing any Services, please check with your bank or credit card issuer for more information about its policies regarding transaction and similar fees. </p>
    <p>It is your sole responsibility to manage your purchases. If you are under 18 (or younger than the age of legal majority in your place of residence), you must obtain your parent’s or guardian’s consent before making any purchases. </p>
    <p> Subject to any applicable additional terms and conditions, all purchases are final and non-refundable. And because our performance begins once you tap buy and we give you immediate access to your purchase, you waive any right you may have under EU or other local law to cancel your purchase once it’s completed or to get a refund. BY ACCEPTING THESE TERMS, YOU AGREE THAT VueMe IS NOT REQUIRED TO PROVIDE A REFUND FOR ANY REASON. </p>

    <p><b>15. Termination.</b></p>
    <p>
        We reserve the right to terminate or restrict your access to or use of the Services, without notice or liability, for any or no reason whatsoever. In addition, we may terminate your Account and any subscription with us by sending notice to you at the e-mail address you provided upon registration. Upon termination of your Account, you will not be entitled to any refund of any unused Credits or other prepaid fees unless otherwise required by applicable law. All decisions regarding the termination of Accounts shall be made by us in our sole discretion. You will not create another account if we have already disabled your account, unless you have our written permission to do so. We are not required, and may be prohibited, from disclosing to you the reason for termination of your Account or subscription.
    </p>
    <p>
        You may terminate your Account and/or subscription with us at any time, and termination will be effective upon receipt of notice from you. WE DO NOT PROVIDE REFUNDS OR CREDITS FOR ANY AMOUNTS PREPAID BY YOU AND YOU WILL NOT RECEIVE ANY REFUND FOR ANY UNUSED DAYS OF ANY PERIODIC SUBSCRIPTION TERM UNLESS OTHERWISE REQUIRED BY LAW.
    </p>
    <p>
        Upon termination of your Account/subscription for any reason, these Terms shall survive termination in accordance with their respective terms.
    </p>





    <p><b>16. Disclaimer of Warranties.</b></p>
    <p>THE SITE AND THE SERVICES (INCLUDING THE APP) ARE PROVIDED “AS IS” AND “AS AVAILABLE,” AND WE EXPRESSLY DISCLAIM ANY IMPLIED WARRANTIES TO THE FULLEST EXTENT PROVIDED BY LAW, INCLUDING BUT NOT LIMITED TO, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR NON-INFRINGEMENT. TO THE EXTENT APPLICABLE LAW PROHIBITS TERMS OF USE FROM DISCLAIMING ANY IMPLIED WARRANTY, SUCH IMPLIED WARRANTY SHALL BE LIMITED TO THE MINIMUM WARRANTY PERIOD REQUIRED BY LAW, AND IF NO SUCH PERIOD IS REQUIRED, THEN THIRTY (30) DAYS FROM FIRST USE OF THE SERVICES. WE CANNOT GUARANTEE AND DO NOT PROMISE ANY SPECIFIC RESULTS FROM USE OF THE SITE OR SERVICES. WITHOUT LIMITING THE FOREGOING, WE DO NOT WARRANT THAT (A) THE SERVICES WILL ALWAYS BE SECURE, ERROR-FREE, OR TIMELY; (B) THE SERVICES WILL ALWAYS FUNCTION WITHOUT DELAYS, DISRUPTIONS, OR IMPERFECTIONS; OR (C) THAT ANY VueMe CONTENT, USER CONTENT, OR INFORMATION YOU OBTAIN ON OR THROUGH THE SERVICES WILL BE TIMELY OR ACCURATE.</p>

    <p><b>17. Limitation of Liability.</b></p>
    <p>IN NO EVENT WILL VueMe AND OUR MANAGING MEMBERS, SHAREHOLDERS, EMPLOYEES, AFFILIATES, LICENSORS, AND SUPPLIERS BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, LOST PROFITS OR REVENUE, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF YOUR ACCESS TO OR USE OF, OR INABILITY TO USE, THE SITE OR SERVICES (INCLUDING THE APP). EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOU AGREE TO WAIVE, AND HEREBY DO WAIVE, ANY LEGAL OR EQUITABLE RIGHTS OR REMEDIES YOU HAVE OR MAY HAVE AGAINST VueMe WITH RESPECT TO THE SERVICES, THE SITE, ALL CONTENT WHICH MAY BE VIEWED THEREON AND ANY INTERACTIONS BETWEEN YOU AND ANY OTHER USER OR PSYCHIC. YOU AGREE THAT IN NO EVENT SHALL OUR LIABILITY TO YOU FOR ANY CLAIM OR CAUSE OF ACTION WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, WHETHER ARISING IN CONTRACT, TORT OR OTHERWISE, EXCEED THE AMOUNT PAID BY YOU TO US, IF ANY, DURING THE 90 DAY PERIOD IMMEDIATELY PRECEDING THE DATE ON WHICH YOU FIRST ASSERT ANY SUCH CLAIM. THE FOREGOING LIMITATIONS SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.</p>

    <p><b>18. Indemnification.</b></p>
    <p>YOU AGREE TO INDEMNIFY AND HOLD VueMe, ITS OWNERS, OPERATORS, AFFILIATES, AND/OR LICENSORS AND THEIR RESPECTIVE SHAREHOLDERS, DIRECTORS, MEMBERS, PARTNERS, OFFICERS, EMPLOYEES, AGENTS, LICENSORS, LICENSEES, SUCCESSORS AND ASSIGNS, HARMLESS TO THE FULLEST EXTENT ALLOWED BY LAW REGARDING ALL LOSS, LIABILITY, CLAIM, DAMAGE, DEMAND OR EXPENSE (INCLUDING, BUT NOT LIMITED TO, REASONABLE ATTORNEY’S FEES, ARISING FROM ANY MATTERS RELATED TO PROVIDER OR USER CONTENT AND/OR USER’S USE OF THE SITE OR SERVICES AND/OR ANY BREACH OR VIOLATION BY YOU OR OTHERS OF THESE TERMS.YOU FURTHER AGREE TO INDEMNIFY AND HOLD US HARMLESS FOR ANY AND ALL CLAIMS, DAMAGES, LIABILITIES, AND EXPENSES IN THE EVENT THAT YOU FIND OTHER USERS’ OR MODELS’ CONTENT TO BE OFFENSIVE, HARMFUL, OBSCENE, INACCURATE AND/OR DECEPTIVE.</p>

    <p><b>19. U.S. Export Controls.</b></p>
    <p>Software and content provided through the Site and the Services (including the App) is subject to United States export controls. No software or content from the Site or the Services (including the App) may be downloaded or otherwise exported or re-exported (a) into (or to a national or resident of) Iraq, Libya, North Korea, Iran, Syria, or any other country to which the United States has embargoed goods; or (b) to anyone on the United States Treasury Department’s list of Specially Designated Nationals or the United States Commerce Department’s Table of Deny Orders. By downloading or using any such software or content, you represent and warrant that you are not located in, under the control of, or a national or resident of, any such country or on any such list. </p>



    <p><b>20. Governing Law; Venue.</b></p>
    <p>These Terms shall be governed by the laws of the State of Florida, without regard to its conflict of laws rules or principles. Users agree to the exclusive jurisdiction and venue in Orange County, Florida for all arbitration and other proceedings arising out of these Terms.</p>

    <p><b>21. Arbitration of Disputes.</b></p>
    <p>ANY CLAIM, DISPUTE, OR CONTROVERSY (WHETHER IN CONTRACT, TORT, OR OTHERWISE, WHETHER PRE-EXISTING, PRESENT OR FUTURE, AND INCLUDING STATUTORY, CONSUMER PROTECTION, COMMON LAW, INTENTIONAL TORT AND EQUITABLE CLAIMS) BETWEEN USERS AND US OR ANY OF OUR AFFILIATES OR THEIR RESPECTIVE AGENTS, EMPLOYEES, PRINCIPALS, SUCCESSORS OR ASSIGNS ARISING FROM OR RELATING TO THESE TERMS, ITS INTERPRETATION, OR THE BREACH, TERMINATION OR VALIDITY HEREOF, OR THE RELATIONSHIPS WHICH RESULT FROM THESE TERMS (INCLUDING TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, RELATIONSHIPS WITH THIRD PARTIES WHO ARE NOT SIGNATORIES TO THIS AGREEMENT), SHALL BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION in accordance with the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (collectively, “AAA Rules”), as modified by these Terms, and will be administered by the AAA before a single arbitrator. The arbitrator shall be empowered to grant whatever relief would be available in a court under law or in equity. Any award of the arbitrator shall be final and binding on each of the parties, and may be entered as a judgment in any court of competent jurisdiction. YOU ACKNOWLEDGE THAT YOU ARE GIVING UP YOUR RIGHTS TO LITIGATE CLAIMS IN A COURT OR BEFORE A JURY WITH RESPECT TO ANY SUCH CLAIMS. Nothing contained in this Section 22 shall be deemed to prohibit us from seeking an injunction or other equitable relief in any court of competent jurisdiction to protect or preserve our rights in and to intellectual property or confidential information. The prevailing party will be entitled to receive from the non-prevailing party its costs relating to the arbitration proceeding including but not limited to, the arbitrator’s fees, attorneys’ fees and costs, witness fees, transcription fees, etc. and sales and use taxes thereon, if any.</p>
    <p>No part of the procedures will be open to the public or media. All evidence discovered or submitted at the hearing is confidential and may not be disclosed, except by written agreement of the parties, pursuant to court order, or unless required by law. Notwithstanding the foregoing, no party will be prevented from submitting to a court of law any information needed to enforce this arbitration agreement, to enforce an arbitration award, or to seek injunctive or equitable relief.
        This arbitration agreement will survive the termination of your relationship with VueMe.

    </p>
    <p><b>22. Class Action Waiver.</b></p>
    <p>You and VueMe each acknowledges and agrees that it is the intent of the parties that arbitration and litigation between the parties will be of the parties’ individual claims, and that none of their respective claims may be arbitrated or litigated on a class-wide basis.</p>
    <p><b>23. Electronic Communications.</b></p>
    <p>By using the Site or the Services, you consent to receiving electronic communications (e.g., e-mail) from us or our affiliates. These communications will include notices about your Account and information concerning or related to the Services. These communications are part of your relationship with us and you receive them as part of your subscription. You agree that any notice, agreements, disclosures or other communications that we send to you electronically will satisfy any legal communication requirements, including but not limited to, any requirements that such communications be in writing.</p>
    <p><b>24. Severability.</b></p>
    <p>If any provision of these Terms is held to be unenforceable under applicable law, such provision shall be excluded from these Terms, and the remainder of these Terms shall be interpreted as if such provision was so excluded and shall be enforceable in accordance with its modified terms.</p>



    <p><b>25. Merger; Translations.</b></p>
    <p>These Terms represent the entire understanding between the parties with respect to the subject matter hereof and supersede all previous understandings, written, oral or implied. Where we have provided you with a translation of the English version of these Terms, you agree that the translation is provided for your convenience only and that the English version of these Terms will govern your relationship with us. If there is any contradiction between the English version of these Terms and any translation, the English version shall take precedence.</p>
    <p><b>26. Force Majeure.</b></p>
    <p>Neither you nor we shall be held responsible for any delay or failure in performance hereunder caused by acts of God (or natural disasters), terrorism, strikes, embargoes, fires, war, or other causes beyond the affected party’s reasonable control.</p>
    <p><b>27. Construction.</b></p>
    <p>The headings used herein are for convenience only and shall not be deemed to define, limit or construe the content of any provision of these Terms. The meanings given to terms defined herein will be equally applicable to both the singular and plural forms of such terms. Whenever the context may require, any pronoun includes the corresponding masculine, feminine and neutral forms.</p>
    <p><b>28. Waiver.</b></p>
    <p>Failure to enforce any provision of these Terms shall not constitute a waiver of any term hereof. No waiver of a breach of any provision of these Terms shall constitute a waiver of any prior, concurrent or subsequent breach of the same or any other provision hereof, and no waiver shall be effective unless granted in writing and signed by an authorized representative of us at our director level or above.</p>
    <p><b>29. Limitation of Claims.</b></p>
    <p>You agree that any claim or cause of action arising out of or related to these Terms or your use of the Site or Services (including the App) must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>
    <p><b>30. Assignment.</b></p>
    <p>You may not resell, assign or transfer any of your rights or obligations under these Terms without our prior written consent. We may resell, assign or transfer our rights and obligations under these Terms at any time without restriction and without notice or consent.</p>
    <p><b>31. Unsolicited Materials and Ideas.</b></p>
    <p>Users may not utilize the Website or any interactions related thereto, to submit any information, ideas, suggestions, concepts, creating ideas or designs, scripts, video or music compositions, suggestions or materials with respect to which a User has any expectation or claim of ownership or proprietary rights (collectively “Submissions”). If you submit any such materials, you agree that it is with the understanding that you will not be entitled to any compensation whatsoever for the ultimate use by Company (including any Affiliate, member, shareholder, partner or employee of Company), any Model, or any other person or entity, for the use of same and by submitting such materials, you are deemed to have renounced any claims of ownership, copyright, trademark, moral rights or other proprietary rights with respect thereto.</p>
    <p><b>32. Binding Agreement.</b></p>
    <p>These Terms shall be binding upon the parties and their successors and permitted assigns.</p>

</div>
@endsection